<?php
namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'category_id' => 1, 'slug' => 'hifz-quran',
                'name_ar' => 'تحفيظ القرآن الكريم', 'name_en' => 'Quran Memorization',
                'desc_ar' => 'برنامج متكامل لحفظ القرآن الكريم مع المراجعة والتثبيت تحت إشراف معلمات مجازات.',
                'desc_en' => 'A comprehensive program for memorizing the Holy Quran with revision and consolidation under the supervision of certified teachers.',
                'icon' => 'fa-book-quran', 'price' => 80, 'level' => 'intermediate', 'audience' => 'women',
                'students_count' => '٢٥٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => '٣ حصص/أسبوع',
                'instructor_ar' => 'أ. سارة أحمد', 'instructor_en' => 'Ms. Sarah Ahmed',
                'instructor_bio_ar' => 'حاصلة على إجازة في القراءات العشر، خبرة ١٠ سنوات في تحفيظ القرآن.',
                'instructor_bio_en' => 'Certified in the ten Qiraat, 10 years of experience in Quran memorization.',
            ],
            [
                'category_id' => 2, 'slug' => 'ahkam-tajweed',
                'name_ar' => 'أحكام التجويد', 'name_en' => 'Tajweed Rules',
                'desc_ar' => 'دراسة أحكام التجويد نظرياً وتطبيقياً برواية حفص عن عاصم.',
                'desc_en' => 'Study of Tajweed rules theoretically and practically with Hafs narration from Asim.',
                'icon' => 'fa-microphone-lines', 'price' => 60, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => '٢٠٠+ طالبة', 'duration' => '٨ أسابيع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. نورهان علي', 'instructor_en' => 'Ms. Nourhan Ali',
                'instructor_bio_ar' => 'معلمة تجويد معتمدة، حاصلة على إجازة برواية حفص.',
                'instructor_bio_en' => 'Certified Tajweed teacher, licensed in Hafs narration.',
            ],
            [
                'category_id' => 3, 'slug' => 'qiraat-ten',
                'name_ar' => 'القراءات العشر', 'name_en' => 'The Ten Qiraat',
                'desc_ar' => 'دراسة القراءات العشر المتواترة بأسانيد متصلة مع الإجازة.',
                'desc_en' => 'Study of the ten mutawatir Qiraat with connected chains of transmission and Ijazah.',
                'icon' => 'fa-book-open', 'price' => 120, 'level' => 'advanced', 'audience' => 'women',
                'students_count' => '١٠٠+ طالبة', 'duration' => '٢٤ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'د. مريم حسن', 'instructor_en' => 'Dr. Maryam Hassan',
                'instructor_bio_ar' => 'دكتورة في القراءات، مجازة بالأسانيد المتصلة.',
                'instructor_bio_en' => 'Doctor of Qiraat, licensed with connected chains.',
            ],
            [
                'category_id' => 4, 'slug' => 'tafsir',
                'name_ar' => 'التفسير وعلوم القرآن', 'name_en' => 'Tafsir & Quranic Sciences',
                'desc_ar' => 'دراسة تفسير القرآن الكريم وعلومه من ناسخ ومنسوخ ومكي ومدني.',
                'desc_en' => 'Study of Quranic exegesis and its sciences including abrogating/abrogated verses and Meccan/Medinan revelations.',
                'icon' => 'fa-lightbulb', 'price' => 50, 'level' => 'intermediate', 'audience' => 'women',
                'students_count' => '١٥٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. فاطمة الزهراني', 'instructor_en' => 'Ms. Fatima Al-Zahrani',
                'instructor_bio_ar' => 'باحثة في علوم القرآن، خبرة ٨ سنوات في التفسير.',
                'instructor_bio_en' => 'Quranic sciences researcher, 8 years of experience in Tafsir.',
            ],
            [
                'category_id' => 4, 'slug' => 'matun',
                'name_ar' => 'المتون العلمية', 'name_en' => 'Scientific Texts',
                'desc_ar' => 'حفظ ودراسة المتون العلمية في العقيدة والفقه والحديث.',
                'desc_en' => 'Memorization and study of scientific texts in creed, jurisprudence, and hadith.',
                'icon' => 'fa-scroll', 'price' => 40, 'level' => 'beginner', 'audience' => 'children',
                'students_count' => '١٢٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. هدى السعيد', 'instructor_en' => 'Ms. Huda Al-Saeed',
                'instructor_bio_ar' => 'متخصصة في تعليم الأطفال، خبرة ١٢ سنة.',
                'instructor_bio_en' => 'Specialized in children education, 12 years of experience.',
            ],
            [
                'category_id' => 1, 'slug' => 'ijazah-hafs',
                'name_ar' => 'إجازات برواية حفص', 'name_en' => 'Ijazah in Hafs',
                'desc_ar' => 'الحصول على إجازة بسند متصل إلى النبي ﷺ برواية حفص عن عاصم.',
                'desc_en' => 'Obtain an Ijazah with a connected chain to the Prophet ﷺ in Hafs narration from Asim.',
                'icon' => 'fa-certificate', 'price' => 150, 'level' => 'advanced', 'audience' => 'women',
                'students_count' => '٨٠+ طالبة', 'duration' => '٢٠ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'د. محمد عبدالله', 'instructor_en' => 'Dr. Muhammad Abdullah',
                'instructor_bio_ar' => 'شيخ مجاز في رواية حفص، خبرة ١٥ سنة في الإجازات.',
                'instructor_bio_en' => 'Certified Sheikh in Hafs narration, 15 years of experience in Ijazah.',
            ],
            [
                'category_id' => 1, 'slug' => 'ijazah-shuba',
                'name_ar' => 'إجازات برواية شعبة', 'name_en' => 'Ijazah in Shuba',
                'desc_ar' => 'الحصول على إجازة بسند متصل برواية شعبة عن عاصم.',
                'desc_en' => 'Obtain an Ijazah with a connected chain in Shuba narration from Asim.',
                'icon' => 'fa-certificate', 'price' => 150, 'level' => 'advanced', 'audience' => 'women',
                'students_count' => '٤٠+ طالبة', 'duration' => '٢٠ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'د. خالد العمري', 'instructor_en' => 'Dr. Khalid Al-Omari',
                'instructor_bio_ar' => 'مجاز في رواية شعبة، خبرة ١٠ سنوات.',
                'instructor_bio_en' => 'Licensed in Shuba narration, 10 years of experience.',
            ],
            [
                'category_id' => 3, 'slug' => 'ijazah-qiraat',
                'name_ar' => 'إجازات في القراءات', 'name_en' => 'Ijazah in Qiraat',
                'desc_ar' => 'إجازات متصلة في القراءات العشر من طريق الشاطبية والدرة.',
                'desc_en' => 'Connected Ijazah in the ten Qiraat via Al-Shatibiyyah and Al-Durrah.',
                'icon' => 'fa-certificate', 'price' => 180, 'level' => 'advanced', 'audience' => 'women',
                'students_count' => '٣٠+ طالبة', 'duration' => '٢٤ أسبوع', 'sessions_per_week' => '٣ حصص/أسبوع',
                'instructor_ar' => 'د. مريم حسن', 'instructor_en' => 'Dr. Maryam Hassan',
                'instructor_bio_ar' => 'دكتورة في القراءات، مجازة بالأسانيد المتصلة.',
                'instructor_bio_en' => 'Doctor of Qiraat, licensed with connected chains.',
            ],
            [
                'category_id' => 2, 'slug' => 'ijazah-jazariya',
                'name_ar' => 'إجازات جزرية', 'name_en' => 'Ijazah in Al-Jazariyyah',
                'desc_ar' => 'إجازة في متن الجزرية في التجويد مع القراءة والأداء.',
                'desc_en' => 'Ijazah in the Jazariyyah text of Tajweed with recitation and performance.',
                'icon' => 'fa-gem', 'price' => 100, 'level' => 'advanced', 'audience' => 'women',
                'students_count' => '٧٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. نورة السالم', 'instructor_en' => 'Ms. Noura Al-Salem',
                'instructor_bio_ar' => 'مجازة في الجزرية، خبرة ٨ سنوات.',
                'instructor_bio_en' => 'Licensed in Al-Jazariyyah, 8 years of experience.',
            ],
            [
                'category_id' => 4, 'slug' => 'fiqh',
                'name_ar' => 'الفقه الإسلامي', 'name_en' => 'Islamic Jurisprudence',
                'desc_ar' => 'دراسة الفقه الإسلامي على المذاهب الأربعة مع التطبيق.',
                'desc_en' => 'Study of Islamic jurisprudence according to the four schools of thought with practical application.',
                'icon' => 'fa-scale-balanced', 'price' => 45, 'level' => 'intermediate', 'audience' => 'women',
                'students_count' => '١٣٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'د. سمية القحطاني', 'instructor_en' => 'Dr. Sumaya Al-Qahtani',
                'instructor_bio_ar' => 'دكتورة في الفقه المقارن، خبرة ١٠ سنوات.',
                'instructor_bio_en' => 'Doctor of comparative jurisprudence, 10 years of experience.',
            ],
            [
                'category_id' => 4, 'slug' => 'seerah',
                'name_ar' => 'السيرة النبوية', 'name_en' => 'Prophetic Biography',
                'desc_ar' => 'دراسة سيرة النبي ﷺ وأخلاقه وشمائله.',
                'desc_en' => 'Study of the Prophet ﷺ biography, his manners and characteristics.',
                'icon' => 'fa-heart', 'price' => 35, 'level' => 'beginner', 'audience' => 'children',
                'students_count' => '١٨٠+ طالبة', 'duration' => '٨ أسابيع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. هند العتيبي', 'instructor_en' => 'Ms. Hind Al-Otaibi',
                'instructor_bio_ar' => 'متخصصة في السيرة النبوية، خبرة ٧ سنوات.',
                'instructor_bio_en' => 'Specialized in prophetic biography, 7 years of experience.',
            ],
            [
                'category_id' => 4, 'slug' => 'arabic-language',
                'name_ar' => 'اللغة العربية', 'name_en' => 'Arabic Language',
                'desc_ar' => 'قواعد النحو والصرف والبلاغة لتيسير فهم القرآن.',
                'desc_en' => 'Rules of grammar, morphology, and rhetoric to facilitate understanding of the Quran.',
                'icon' => 'fa-language', 'price' => 55, 'level' => 'intermediate', 'audience' => 'all',
                'students_count' => '١٦٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. منال الشريف', 'instructor_en' => 'Ms. Manal Al-Sharif',
                'instructor_bio_ar' => 'معلمة لغة عربية معتمدة، خبرة ١٠ سنوات.',
                'instructor_bio_en' => 'Certified Arabic teacher, 10 years of experience.',
            ],
            [
                'category_id' => 4, 'slug' => 'aqeedah',
                'name_ar' => 'العقيدة الإسلامية', 'name_en' => 'Islamic Creed',
                'desc_ar' => 'دراسة العقيدة الإسلامية الصحيحة وأصول الإيمان.',
                'desc_en' => 'Study of the correct Islamic creed and the foundations of faith.',
                'icon' => 'fa-star-and-crescent', 'price' => 40, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => '١١٠+ طالبة', 'duration' => '١٠ أسابيع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. ليلى الراشد', 'instructor_en' => 'Ms. Layla Al-Rashed',
                'instructor_bio_ar' => 'متخصصة في العقيدة، خبرة ٦ سنوات.',
                'instructor_bio_en' => 'Specialized in creed, 6 years of experience.',
            ],
            [
                'category_id' => 4, 'slug' => 'hadith',
                'name_ar' => 'الحديث الشريف', 'name_en' => 'Prophetic Hadith',
                'desc_ar' => 'دراسة الحديث النبوي الشريف والعلوم المرتبطة به.',
                'desc_en' => 'Study of the noble prophetic hadith and its related sciences.',
                'icon' => 'fa-message', 'price' => 50, 'level' => 'intermediate', 'audience' => 'women',
                'students_count' => '٩٠+ طالبة', 'duration' => '١٢ أسبوع', 'sessions_per_week' => 'حصتين/أسبوع',
                'instructor_ar' => 'أ. أمل الحربي', 'instructor_en' => 'Ms. Amal Al-Harbi',
                'instructor_bio_ar' => 'باحثة في الحديث وعلومه، خبرة ٩ سنوات.',
                'instructor_bio_en' => 'Hadith sciences researcher, 9 years of experience.',
            ],
            [
                'category_id' => 1, 'slug' => 'khatma',
                'name_ar' => 'مشروع الختمة', 'name_en' => 'Quran Completion Project',
                'desc_ar' => 'برنامج ختمة قرآن كامل مع التلاوة والتصحيح والتجويد.',
                'desc_en' => 'Complete Quran completion program with recitation, correction, and Tajweed.',
                'icon' => 'fa-list', 'price' => 70, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => '٣٠٠+ طالبة', 'duration' => '٢٤ أسبوع', 'sessions_per_week' => '٥ حصص/أسبوع',
                'instructor_ar' => 'أ. سارة أحمد', 'instructor_en' => 'Ms. Sarah Ahmed',
                'instructor_bio_ar' => 'حاصلة على إجازة في القراءات العشر، خبرة ١٠ سنوات.',
                'instructor_bio_en' => 'Certified in the ten Qiraat, 10 years of experience.',
            ],
            [
                'category_id' => 5, 'slug' => 'languages-service',
                'name_ar' => 'اللغات واللغويات', 'name_en' => 'Languages & Linguistics',
                'desc_ar' => 'تعليم اللغة العربية لغير الناطقين بها وبرامج تأسيس لغوي شاملة.',
                'desc_en' => 'Teaching Arabic to non-native speakers and comprehensive language foundation programs.',
                'icon' => 'fa-language', 'price' => 0, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => 'مميز',
            ],
            [
                'category_id' => 5, 'slug' => 'coding-service',
                'name_ar' => 'التكنولوجيا والبرمجة', 'name_en' => 'Technology & Programming',
                'desc_ar' => 'تطوير مهارات المستقبل للأطفال في بيئة تربوية محافظة.',
                'desc_en' => 'Developing future skills for children in a conservative educational environment.',
                'icon' => 'fa-laptop-code', 'price' => 0, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => 'مميز',
            ],
            [
                'category_id' => 5, 'slug' => 'educational-support',
                'name_ar' => 'الدعم التربوي', 'name_en' => 'Educational Support',
                'desc_ar' => 'جلسات استشارية للأمهات لتطوير أساليب التربية والتعامل.',
                'desc_en' => 'Consultative sessions for mothers to develop parenting and interaction methods.',
                'icon' => 'fa-hands-holding-child', 'price' => 0, 'level' => 'beginner', 'audience' => 'all',
                'students_count' => 'مميز',
            ],
        ];

        foreach ($courses as $data) {
            Course::create($data);
        }
    }
}
